---
# Course CRD
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: courses.nchc.ai
spec:
  group: nchc.ai
  version: v1alpha1
  names:
    kind: Course
    plural: courses
  scope: Namespaced
